/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRM;

import java.awt.Panel;
import BUS.khachhangBUS;
import DTO.khachhangDTO;
import java.awt.Font;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dat
 */
public class khachhangFRM extends javax.swing.JFrame {

    /**
     * Creates new form khachhangFRM
     * @throws java.sql.SQLException
     */
    ArrayList<khachhangDTO> listKH;
    public int ChooseID;
    DefaultTableModel model;
    private TableRowSorter<TableModel> rowSorter;
    
    public void showListKhachhang() throws SQLException
    {
        khachhangBUS nv = new khachhangBUS();
        try 
        {
            listKH = nv.getAllKhachHang();
            
            if(listKH!=null)
            {
                model = (DefaultTableModel) tbl_khachhang.getModel();
                listKH.forEach((lx) -> 
                {
                    model.addRow(new Object[]{lx.getId(),lx.getName(),lx.getGioitinh(),lx.getDiachi(),lx.getSdt(),false});
                });
            tbl_khachhang.setModel(model);
            }
            else
            {
                System.out.println("Không thêm được dữ liệu vào List || khachhangGUI");
            }
        } catch (SQLException ex) {
            Logger.getLogger(khachhangFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
        rowSorter = new TableRowSorter<>(tbl_khachhang.getModel());
        TableSortFilter();
    }
    private void TableSortFilter() {
        tbl_khachhang.setRowSorter(rowSorter);
        txt_timkiem.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txt_timkiem.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                }
                else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" +text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txt_timkiem.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }
    public int getmaxid(ArrayList<khachhangDTO> l)
    {
        if (l.size()!=0)
            return l.get(l.size()-1).getId();
        return -1;
    }
    public khachhangFRM() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        btn_luu.setVisible(false);
        btn_ketthuc.setVisible(false);
        lbl_edit.setVisible(false);
        setTitle("Quản lý khách hàng");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tenkhachhang = new javax.swing.JTextField();
        cmb_gioitinh = new javax.swing.JComboBox<>();
        txt_diachi = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_ketthuc = new javax.swing.JButton();
        lbl_edit = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        lbl_timkiem = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Trị Khách Hàng");

        jLabel3.setText("Tên Khách Hàng");

        jLabel5.setText("Giới Tính");

        jLabel6.setText("Địa Chỉ");

        jLabel7.setText("Số Điện Thoại");

        txt_tenkhachhang.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        cmb_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        txt_sdt.setText("0");

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Địa Chỉ", "Số Điện Thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_khachhang);
        if (tbl_khachhang.getColumnModel().getColumnCount() > 0) {
            tbl_khachhang.getColumnModel().getColumn(1).setResizable(false);
            tbl_khachhang.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Cập nhật");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_ketthuc.setText("Kết thúc");
        btn_ketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ketthucActionPerformed(evt);
            }
        });

        lbl_edit.setText("Chọn 1 dòng bên dưới để cập nhật");

        lbl_timkiem.setText("Tìm kiếm");

        btn_thongke.setText("Tìm kiếm");
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_timkiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lbl_edit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ketthuc)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cmb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(btn_thongke)
                    .addComponent(btn_luu)
                    .addComponent(btn_ketthuc)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_timkiem)
                    .addComponent(lbl_edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // TODO add your handling code here:
        
        try {
            
            showListKhachhang();
        } catch (SQLException ex) {
            Logger.getLogger(khachhangFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbl_khachhang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(tbl_khachhang.getSelectedRow() >=0)
                {
                    ChooseID  = Integer.parseInt(tbl_khachhang.getValueAt(tbl_khachhang.getSelectedRow(), 0).toString());
                    txt_tenkhachhang.setText(tbl_khachhang.getValueAt(tbl_khachhang.getSelectedRow(), 1).toString());
                    cmb_gioitinh.setSelectedItem(tbl_khachhang.getValueAt(tbl_khachhang.getSelectedRow(), 2).toString());
                    txt_diachi.setText(tbl_khachhang.getValueAt(tbl_khachhang.getSelectedRow(), 3).toString());
                    txt_sdt.setText(tbl_khachhang.getValueAt(tbl_khachhang.getSelectedRow(), 4).toString());
                }
            }
        });
    }//GEN-LAST:event_formWindowOpened
    
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
            
            if(JOptionPane.showConfirmDialog(this, "Bạn muốn thêm?", "??", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            {
                try 
                    {
                        String diachi = txt_diachi.getText();
                        String gioitinh = cmb_gioitinh.getSelectedItem().toString();
                        String sdt = txt_sdt.getText();
                        int id = getmaxid(listKH)+1;
                        String name = txt_tenkhachhang.getText();
                        khachhangDTO nv = new khachhangDTO(diachi,gioitinh,sdt,id,name);
                        khachhangBUS bus = new khachhangBUS();
                        try {
                            bus.Insert(nv);
                        } catch (SQLException ex) {
                            Logger.getLogger(khachhangFRM.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        listKH.add(nv);
                        DefaultTableModel model = (DefaultTableModel) tbl_khachhang.getModel();
                        model.addRow(new Object[]{nv.getId(),nv.getName(),nv.getGioitinh(),nv.getDiachi(),nv.getSdt()});
                    } 
                catch (NumberFormatException e)
                    {
                        JOptionPane.showMessageDialog(this,"Số điện thoại không được bỏ trống hoặc có chữ cái");
                    }
            }
    }//GEN-LAST:event_btn_themActionPerformed

    public void editModel(khachhangDTO nv, int id)
    {
        int row = returnposition(id);
        model.setValueAt(nv.getName(),row,1);
        model.setValueAt(nv.getGioitinh(),row,2);
        model.setValueAt(nv.getDiachi(),row,3);
        model.setValueAt(nv.getSdt(),row,4);
    }
    private int returnposition(int id) {
        for(int i=0; i<listKH.size(); i++) {
            if (listKH.get(i).getId()==id)
                return i;
        }
        return -1;
    }
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Bạn muốn sửa?", "???",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            try
            {
                if(tbl_khachhang.getSelectedRow()<0)
                {
                    JOptionPane.showMessageDialog(this, "Chưa Có khách hàng được chọn");
                }
                else
                {
                    String diachi = txt_diachi.getText();
                    String gioitinh = cmb_gioitinh.getSelectedItem().toString();
                    String sdt = txt_sdt.getText();
                    String name = txt_tenkhachhang.getText();
                    int id = Integer.parseInt(tbl_khachhang.getValueAt(tbl_khachhang.getSelectedRow(), 0).toString());
                    khachhangDTO nv = new khachhangDTO(diachi, gioitinh, sdt, id, name);
                    khachhangBUS bus = new khachhangBUS();
                    bus.Edit(nv);
                    listKH.set(returnposition(id), nv);
                    editModel(nv, id);
                }
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Số Điện Thoại Không Được Bỏ Trống Hoặc Có Chữ Cái");
            }
        }
        
    }//GEN-LAST:event_btn_luuActionPerformed
    
    private void btn_ketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ketthucActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Hủy sửa?","???", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            btn_them.setVisible(true);
            btn_sua.setVisible(true);
            btn_xoa.setVisible(true);
            btn_luu.setVisible(false);
            btn_ketthuc.setVisible(false);
            lbl_edit.setVisible(false);
            
        }
        else
        {
            btn_luu.setVisible(true);
            btn_ketthuc.setVisible(true);
        }
    }//GEN-LAST:event_btn_ketthucActionPerformed
    
    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        lbl_edit.setVisible(true);
        btn_luu.setVisible(true);
        btn_ketthuc.setVisible(true);
        btn_them.setVisible(false);
        btn_sua.setVisible(false);
        btn_xoa.setVisible(false);
        
        
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Bạn muốn xóa?", "???",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            khachhangBUS NVD = new khachhangBUS();
            listKH.remove(tbl_khachhang.getSelectedRow());
            model.removeRow(tbl_khachhang.getSelectedRow());
            try {
                NVD.Delete(ChooseID);
            } catch (SQLException ex) {
                Logger.getLogger(khachhangFRM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        // TODO add your handling code here:
        javax.swing.JTextField content = new javax.swing.JTextField("",10);
        JComboBox cmb_gioitinh = new JComboBox(new String[]{"Tất cả","Nam","Nữ"});
        Object obCa= new Object[]{"Chọn giới tính:",cmb_gioitinh};
        JOptionPane.showMessageDialog(null,obCa);
        String gioitinh=cmb_gioitinh.getSelectedItem().toString();
        khachhangBUS bus = new khachhangBUS();
        ArrayList<khachhangDTO> kh;
        try {
                kh = bus.getKhachHangByTK(gioitinh,this.listKH);
                HienThiDanhSachKhachHang(kh);
            } catch (SQLException ex) {
            Logger.getLogger(khachhangFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuFRM menu = new MenuFRM();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void HienThiDanhSachKhachHang(ArrayList<khachhangDTO> ds){
        this.model.setRowCount(0);
        Vector data;
        for(khachhangDTO kh:ds){
            data = new Vector();
            data.add(kh.getId());
            data.add(kh.getName());
            data.add(kh.getGioitinh());
            data.add(kh.getDiachi());
            data.add(kh.getSdt());
            this.model.addRow(data);
        }
        this.tbl_khachhang.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(khachhangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(khachhangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(khachhangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(khachhangFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new khachhangFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ketthuc;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cmb_gioitinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_edit;
    private javax.swing.JLabel lbl_timkiem;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenkhachhang;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    

}