/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRM;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import SUPPORT.WriteToPDF;
import SUPPORT.WriteExcelFile;
import SUPPORT.ReadExcelFile;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author xenov
 */
public class NhanVienFRM extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private TextField txtNgaySinh = new TextField("",10);
    private TextField txtCa = new TextField("",10);
    /**
     * Creates new form NhanVienFRM
     */
    public NhanVienFRM() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbNam);
        rbNam.setSelected(true);
        bg.add(rbNu);
        docNhanVien();
        taoNgaySinh();
        setTitle("Quản lý nhân viên");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JS = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        cbNgay = new javax.swing.JComboBox<>();
        cbThang = new javax.swing.JComboBox<>();
        cbNam = new javax.swing.JComboBox<>();
        lblHo = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblCa = new javax.swing.JLabel();
        cbCaLam = new javax.swing.JComboBox<>();
        cbThu = new javax.swing.JComboBox<>();
        lblLuong = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMouseClicked(evt);
            }
        });
        JS.setViewportView(jt);

        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnDatLai.setText("Đặt lại");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblMa.setText("Mã");

        lblNgaySinh.setText("Ngày sinh");

        cbNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));

        cbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHo.setText("Họ");

        lblGioiTinh.setText("Giới tính");

        rbNam.setText("Nam");

        rbNu.setText("Nữ");

        lblTen.setText("Tên");

        lblCa.setText("Ca làm");

        cbCaLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Chiều", "Tối" }));

        cbThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7", "Chủ nhật" }));

        lblLuong.setText("Lương");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMa)
                            .addComponent(lblHo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblLuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCa)
                            .addComponent(lblNgaySinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGioiTinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbNu)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMa)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCa)
                            .addComponent(cbCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHo)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNgaySinh)
                        .addComponent(cbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbNam)
                        .addComponent(rbNu)
                        .addComponent(lblGioiTinh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTen)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuong)))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mnFile.setText("File");
        mnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Làm mới danh sách");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem1);

        jMenu1.setText("Đọc file Excel");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nhập dữ liệu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Ghi mới Database");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Cập nhật Database");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        mnFile.add(jMenu1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Ghi file Excel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem3);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("In báo cáo pdf");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem8);

        jMenuBar1.add(mnFile);

        jMenu2.setText("Edit");

        jMenuItem4.setText("Tìm kiếm theo mã họ tên");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Tìm kiếm theo ca làm");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Tìm kiếm theo lương");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem11.setText("Thống kê");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addGap(14, 14, 14)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDatLai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JS)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnDatLai)
                    .addComponent(btnTimKiem)
                    .addComponent(btnThoat)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(JS, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMouseClicked
        // TODO add your handling code here:
        int i = jt.getSelectedRow();
        if(i>=0){
            setTextFieldValue(jt.getValueAt(i,0)+"",jt.getValueAt(i,1)+"",jt.getValueAt(i,2)+"",jt.getValueAt(i,3)+"",jt.getValueAt(i,4)+"",jt.getValueAt(i,5)+"",jt.getValueAt(i,6)+"");
        }
    }//GEN-LAST:event_jtMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
            if(!isValidToAdd())  
                return;
            if(!isValidDateFormat()){
                JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
                return;
            }
            NhanVienDTO nv = getFromTextField();
            Vector head = setVector(nv);
            NhanVienBUS bus = new NhanVienBUS();
            int check = bus.them(nv);
            if(check == 1){
                model.addRow(head);
                jt.setModel(model);
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            }else{
                JOptionPane.showMessageDialog(null, "Mã đã tồn tại. Thêm thất bại");
            } 
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int i = jt.getSelectedRow();
        if(i>=0){
            if(!isValidToAdd())
                return;
            if(!isValidDateFormat()){
                JOptionPane.showMessageDialog(null, "Ngày sinh không hợp lệ!");
                return;
            }
            int result = JOptionPane.showConfirmDialog(null, "Xác nhận sửa ?","Xác nhận",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                NhanVienDTO nv = getFromTextField();
                NhanVienBUS bus = new NhanVienBUS();
                int check = bus.sua(nv, i);
                if(check == 1){
                    setModelValue(nv,i);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = jt.getSelectedRow();
        if(i>=0){
            int result = JOptionPane.showConfirmDialog(null, "Xác nhận xóa ?", "Xác nhận",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                NhanVienBUS bus = new NhanVienBUS();
                int check = bus.xoa(i);  
                if(check == 1){
                    model.removeRow(i);
                    jt.setModel(model);
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                } 
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Xác nhận thoát ?","Thoát",JOptionPane.OK_CANCEL_OPTION);
        if(exit == JOptionPane.OK_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        // TODO add your handling code here:            
            setTextFieldValue("","","","01/01/2002","Nam","Sáng Thứ 2","");
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String result = JOptionPane.showInputDialog(null, "Nhập tìm kiếm", "Tìm kiếm",JOptionPane.INFORMATION_MESSAGE);
        if(result == null) return;
        NhanVienBUS bus = new NhanVienBUS();
        showOnTable(bus.timKiem(result));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void mnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnFileActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        docNhanVien();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Ghi file Excel 
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ArrayList<NhanVienDTO> ds = new ArrayList<NhanVienDTO>();
        for(int i=0;i<jt.getRowCount();i++){
            NhanVienDTO nv = getNhanVienFromModel(i);
            ds.add(nv);
        }
        JFileChooser choose = new JFileChooser();
        int result = choose.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File file = choose.getSelectedFile();
            WriteExcelFile wr = new WriteExcelFile(file.getAbsolutePath(), ds);
            JOptionPane.showMessageDialog(null, new Object[]{"Ghi file excel thành công:",file.getAbsolutePath()});
        }
            
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        btnTimKiemActionPerformed(evt);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        //ca lam tim kiem
        JComboBox ca = new JComboBox(new String[]{"Tất cả","Sáng","Chiều","Tối"});
        JComboBox thu = new JComboBox(new String[]{"Tất cả","Thứ 2","Thứ 3","Thứ 4","Thứ 5","Thứ 6","Thứ 7","Chủ nhật"});
        Object[] ob= new Object[]{"Chọn ca làm:",ca,thu};
        JOptionPane.showMessageDialog(null,ob);
        String result = ca.getSelectedItem()+"" + thu.getSelectedItem();
        NhanVienBUS bus = new NhanVienBUS();
        showOnTable(bus.timKiemTheoCaLam(result));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        NhanVienBUS bus = new NhanVienBUS();
        //lay thong tin luong
        int tongluong = 0;
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        int[] luong = new int[5];
        int[] buoi = new int[]{0,0,0};
        int[] thu = new int[]{0,0,0,0,0,0,0};
        for(NhanVienDTO nv:bus.ds){
            tongluong += nv.getLuong();
            if(min > nv.getLuong()) min = nv.getLuong();
            if(max < nv.getLuong()) max = nv.getLuong();
            
            String[] day = nv.getCa().split(" ");
            switch(day[0]){
                case "Sáng":
                    buoi[0]++;
                    break;
                case "Chiều":
                    buoi[1]++;
                    break;
                case "Tối":
                    buoi[2]++;
                    break;
            }
            switch(day[2]){
                case "2":
                    thu[0]++;
                    break;
                case "3":
                    thu[1]++;
                    break;
                case "4":
                    thu[2]++;
                    break;
                case "5":
                    thu[3]++;
                    break;
                case "6":
                    thu[4]++;
                    break;
                case "7":
                    thu[5]++;
                    break;
                case "Nhật":
                    thu[6]++;
                    break;
            }
        }
        luong[0]= bus.ds.size();
        luong[1] = tongluong;
        luong[2] = luong[1]/luong[0];
        luong[3] = min;
        luong[4] = max;
        JFileChooser choose = new JFileChooser();
        int result = choose.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File file = choose.getSelectedFile();
            //PrintReportNhanVien pr = new PrintReportNhanVien(file.getAbsolutePath(), tongso, tongluong, min, max);
            try{
                WriteToPDF report = new WriteToPDF(file.getAbsolutePath(),luong,buoi,thu);
            }catch(Exception e){e.printStackTrace();}
            JOptionPane.showMessageDialog(null,new Object[]{"Ghi báo cáo thành công",file.getAbsolutePath()});
        }
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        //Tim theo luong
        JComboBox from = new JComboBox(new String[]{"1000000","3000000","5000000","7000000","9000000","11000000","13000000","15000000"});
        JComboBox to = new JComboBox(new String[]{"2000000","4000000","6000000","8000000","10000000","12000000","14000000","16000000"});
        from.setEditable(true);
        to.setEditable(true);
        Object[] ob= new Object[]{"Lương từ",from,"đến",to};
        JOptionPane.showMessageDialog(null,ob);
        NhanVienBUS bus = new NhanVienBUS();
        showOnTable(bus.timKiemTheoLuong(Integer.parseInt(from.getSelectedItem().toString()),Integer.parseInt(to.getSelectedItem().toString())));
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    //Doc file Excel
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileDialog = new JFileChooser();
        int result = fileDialog.showOpenDialog(null);
        if(result == fileDialog.APPROVE_OPTION){
            File file = fileDialog.getSelectedFile();
            ReadExcelFile read = new ReadExcelFile(file.getAbsolutePath());
            try{
                ArrayList<NhanVienDTO> ds = read.readData();
                showOnTable(ds);
            }catch(Exception e){}
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        NhanVienBUS bus = new NhanVienBUS();
        bus.DeleteAll();
        ArrayList<NhanVienDTO> ds = new ArrayList<NhanVienDTO>();
        for(int i=0;i<jt.getRowCount();i++){
            NhanVienDTO nv = getNhanVienFromModel(i);
            ds.add(nv);
        }
        for(int i=0;i<ds.size();i++){
            bus.them(ds.get(i));
        }
        JOptionPane.showMessageDialog(null, "Thành công");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        NhanVienBUS bus = new NhanVienBUS();
        ArrayList<NhanVienDTO> ds = new ArrayList<NhanVienDTO>();
        for(int i=0;i<jt.getRowCount();i++){
            NhanVienDTO nv = getNhanVienFromModel(i);
            ds.add(nv);
        }
        int recordedItem = 0;
        for(int i=0;i<ds.size();i++){
            recordedItem += bus.them(ds.get(i));
        }
        if(recordedItem == 0) JOptionPane.showMessageDialog(null, "Không có bản ghi nào được thêm");
            else
        JOptionPane.showMessageDialog(null, recordedItem + " bản ghi đã được thêm!");
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    //Thong ke--------------------------------------------------------------
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        javax.swing.JTextField content = new javax.swing.JTextField("",10);
        content.setFont(new Font("Arial",Font.PLAIN,14));
        Panel panelCa = new Panel(new GridLayout(1,2));
        JComboBox ca = new JComboBox(new String[]{"Tất cả","Sáng","Chiều","Tối"});
        JComboBox thu = new JComboBox(new String[]{"Tất cả","Thứ 2","Thứ 3","Thứ 4","Thứ 5","Thứ 6","Thứ 7","Chủ nhật"});
        panelCa.add(ca);
        panelCa.add(thu);
        Object[] obCa= new Object[]{"Chọn ca làm:",panelCa};
        JComboBox from = new JComboBox(new String[]{"1000000","3000000","5000000","7000000","9000000","11000000","13000000","15000000"});
        JComboBox to = new JComboBox(new String[]{"2000000","4000000","6000000","8000000","10000000","12000000","14000000","16000000"});
        from.setEditable(true);
        to.setEditable(true);
        Panel panelCb = new Panel(new GridLayout(2,2));
        panelCb.add(new JLabel("Lương từ"));
        panelCb.add(from);
        panelCb.add(new JLabel("đến"));
        panelCb.add(to);
        Object[] obLuong= new Object[]{panelCb};
        
        JTextField txtSoLuong = new JTextField("",3);
        JTextField txtTongTien = new JTextField("",3);
        JLabel lblSoLuong = new JLabel("Tổng số nhân viên");
        JLabel lblTongTien = new JLabel("Tổng lương");
        Panel panelPopUp = new Panel(new GridLayout(1,2));
        Panel panelPopUp1 = new Panel(new GridLayout(1,2));
        panelPopUp.add(lblSoLuong);
        panelPopUp.add(txtSoLuong);
        panelPopUp1.add(lblTongTien);
        panelPopUp1.add(txtTongTien);
        JButton btnThongKe = new JButton("Thống kê");
        NhanVienBUS bus = new NhanVienBUS();
        btnThongKe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ArrayList<NhanVienDTO> list = bus.thongKe(content.getText(),ca.getSelectedItem()+""+thu.getSelectedItem(),Integer.parseInt(from.getSelectedItem().toString()),Integer.parseInt(to.getSelectedItem().toString()));
                txtSoLuong.setText(list.size()+"");
                int tong = 0;
                for(NhanVienDTO nv:list){
                    tong += nv.getLuong();
                }
                txtTongTien.setText(tong+"");
                ca.setVisible(true);
                ca.setLightWeightPopupEnabled(false); //
                thu.setVisible(true);
                thu.setLightWeightPopupEnabled(false); //
                from.setVisible(true);
                from.setLightWeightPopupEnabled(false); //
                to.setVisible(true);
                to.setLightWeightPopupEnabled(false); //
                
            }
        });
        Object panel = new Object[]{"Từ khóa",content,obCa,obLuong,btnThongKe,panelPopUp,panelPopUp1};
        JOptionPane.showMessageDialog(null,panel);
        showOnTable(bus.thongKe(content.getText(),ca.getSelectedItem()+""+thu.getSelectedItem(),Integer.parseInt(from.getSelectedItem().toString()),Integer.parseInt(to.getSelectedItem().toString())));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuFRM menu = new MenuFRM();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean isValidToAdd(){
        boolean ok = true;
        if(txtMa.getText().trim().equals("")) ok = false;
        if(txtHo.getText().trim().equals("")) ok = false;
        if(txtTen.getText().trim().equals("")) ok = false;
        txtCa.setText(cbCaLam.getSelectedItem().toString() + " " + cbThu.getSelectedItem().toString());
        if(txtLuong.getText().trim().equals("")) ok = false;
        if(ok == false){
            JOptionPane.showMessageDialog(null, "Bạn phải điền đầy đủ thông tin !");
            return ok;
        }
        if(!isNumberic(txtLuong.getText())){
            ok = false;
            JOptionPane.showMessageDialog(null, "Lương không hợp lệ !");
        }
        return ok;
    }
    public void docNhanVien(){
       NhanVienBUS bus = new NhanVienBUS();
       try{
           bus.docNhanVien();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Lỗi kết nối đến Database.");
           return;
       }
       Vector header = new Vector();
       header.add("Mã");
       header.add("Họ");
       header.add("Tên");
       header.add("Ngày sinh");
       header.add("Giới tính");
       header.add("Ca làm");
       header.add("Lương");
       model = new DefaultTableModel(header,0){
            public boolean isCellEditable(int row, int column)
                {
                  return false;//This causes all cells to be not editable
                }
       };
       jt.setAutoCreateRowSorter(true);	
       showOnTable(bus.ds);
    }
    public void showOnTable(ArrayList<NhanVienDTO> ds){
        model.setRowCount(0);
        for(NhanVienDTO nv:ds){
           Vector data = setVector(nv);
           model.addRow(data);
       }
       jt.setModel(model);
    }
    public void taoNgaySinh(){
        Vector nam = new Vector();
        int year = Calendar.getInstance().get(Calendar.YEAR)-17;
        for(int i=year; i>=1960;i--){
            nam.add(i);
        }
        cbNam.setModel(new DefaultComboBoxModel(nam));
    }
    public void setDate(String ngaysinh){
        String[] ng = ngaysinh.split("/");
        cbNgay.setSelectedItem(Integer.parseInt(ng[0])+"");     
        cbThang.setSelectedIndex(Integer.parseInt(ng[1])-1);
        cbNam.setSelectedItem(Integer.parseInt(ng[2]));
    }
    public NhanVienDTO getFromTextField(){
            NhanVienDTO nv = new NhanVienDTO();
            nv.setMa(txtMa.getText().trim());
            nv.setHo(txtHo.getText().trim());
            nv.setTen(txtTen.getText().trim());
            nv.setNgaysinh(txtNgaySinh.getText().trim());
            nv.setGioitinh(rbNam.isSelected()?true:false);
            nv.setCa(txtCa.getText().trim());
            nv.setLuong(Integer.parseInt(txtLuong.getText()));
            return nv;
    }
    public Vector setVector(NhanVienDTO nv){
            Vector head = new Vector();
            head.add(nv.getMa());
            head.add(nv.getHo());
            head.add(nv.getTen());
            head.add(nv.getNgaysinh());
            head.add(nv.isGioitinh()?"Nam":"Nữ");
            head.add(nv.getCa());
            head.add(nv.getLuong());
            return head;
    }
    public void setModelValue(NhanVienDTO nv, int i){
        model.setValueAt(nv.getMa(),i,0);
        model.setValueAt(nv.getHo(),i,1);
        model.setValueAt(nv.getTen(),i,2);
        model.setValueAt(nv.getNgaysinh(),i,3);
        model.setValueAt(nv.isGioitinh()?"Nam":"Nữ",i,4);
        model.setValueAt(nv.getCa(),i,5);
        model.setValueAt(nv.getLuong(),i,6);
        jt.setModel(model);            
    }
    public NhanVienDTO getNhanVienFromModel(int i){
            NhanVienDTO nv = new NhanVienDTO();
            nv.setMa(jt.getValueAt(i,0)+"");
            nv.setHo(jt.getValueAt(i,1)+"");
            nv.setTen(jt.getValueAt(i,2)+"");
            nv.setNgaysinh(jt.getValueAt(i,3)+"");
            nv.setGioitinh((jt.getValueAt(i,4)+"").equals("Nam")?true:false);
            nv.setCa(jt.getValueAt(i,5)+"");
            nv.setLuong(Integer.parseInt(jt.getValueAt(i,6)+"")); 
            return nv;
    }
    public void setTextFieldValue(String ma, String ho, String ten, String ngaysinh,String gioitinh,String calam,String luong){
            txtMa.setText(ma);
            txtHo.setText(ho);
            txtTen.setText(ten);
            txtNgaySinh.setText(ngaysinh);
            setDate(txtNgaySinh.getText());
            if((gioitinh).toLowerCase().equals("nam")){
                rbNam.setSelected(true);
            }else rbNu.setSelected(true);
            txtCa.setText(calam);
            String[] ca = txtCa.getText().split(" ");
            cbCaLam.setSelectedItem(ca[0]);
            cbThu.setSelectedItem(ca[1] + " " + ca[2]);
            txtLuong.setText(luong);
    }
    public boolean isValidDateFormat(){
        int ngay = Integer.parseInt(cbNgay.getSelectedItem().toString());
        int thang = (cbThang.getSelectedIndex()+1);
        txtNgaySinh.setText((ngay>=10?ngay:"0"+ngay) + "/" + (thang>=10?thang:"0"+thang) + "/" + cbNam.getSelectedItem());
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false);
        try{
            Date da = df.parse(txtNgaySinh.getText());
        }catch(ParseException e){
            return false;
        }
        return true;
    }
    public boolean isNumberic(String str){
        return str.matches("^\\d+$");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JS;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbCaLam;
    private javax.swing.JComboBox<String> cbNam;
    private javax.swing.JComboBox<String> cbNgay;
    private javax.swing.JComboBox<String> cbThang;
    private javax.swing.JComboBox<String> cbThu;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jt;
    private javax.swing.JLabel lblCa;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblTen;
    private javax.swing.JMenu mnFile;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
