
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NGOC BAU
 */
public class WaitRoom extends javax.swing.JFrame {
    String id;
    Socket s;
    BufferedReader in ;
    BufferedWriter out;
    String nameUser2;
    /**
     * Creates new form WaitRoom
     */
    public WaitRoom() {
        //initComponents();
    }
    WaitRoom (String id, Socket s){
        this.id = id;  
        this.s=s;
        try {
            initComponents();
            this.setTitle("Client - "+id);
            lbwelcome.setText("Xin chào, "+id);
            pYes.setVisible(false);
            pNo.setVisible(false);
            in = new BufferedReader(new InputStreamReader(s.getInputStream()));
            out = new BufferedWriter(new OutputStreamWriter(s.getOutputStream()));
            out.write("Pair:Request");//Yeu cau ghep doi.
            out.newLine();
            out.flush();
            new Read().start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    class Read extends Thread {
        public void run(){
            while (true){
                try {
                    String messFromServer  = in.readLine();
                    System.out.println("Server send: "+messFromServer);
                    if(messFromServer.contains("Pair:")) messFromServer = messFromServer.split(":")[1];
                    if(messFromServer.equals("wait")){                        
                        lbThongBao1.setText("Đang tìm kiếm.......!");
                        lbThongBao.setText(".............");
                        pYes.setVisible(false);
                        pNo.setVisible(false);                                                  
                    }else if(messFromServer.contains("chat;")){
                        nameUser2 = messFromServer.split(";")[1];                        
                        openChat();                        
                        break;
                    }else{                        
                        lbThongBao1.setText(messFromServer+" đang rảnh!!!");
                        lbThongBao.setText("Bạn có muốn Chat với người này không?");
                        pYes.setVisible(true);
                        pNo.setVisible(true);                        
                    }                     
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            }
        }
    }
    private void openChat(){
        new ClientGUI(id, s, nameUser2).setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbwelcome = new javax.swing.JLabel();
        lbThongBao = new javax.swing.JLabel();
        pYes = new javax.swing.JPanel();
        lbYes = new javax.swing.JLabel();
        pNo = new javax.swing.JPanel();
        lbNo = new javax.swing.JLabel();
        lbThongBao1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 50, 74));

        lbwelcome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbwelcome.setForeground(new java.awt.Color(255, 255, 255));
        lbwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbwelcome.setText("Xin chào, Ngọc báu!");

        lbThongBao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbThongBao.setForeground(new java.awt.Color(255, 255, 255));
        lbThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongBao.setText("............");

        pYes.setBackground(new java.awt.Color(0, 204, 204));
        pYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pYesMouseClicked(evt);
            }
        });

        lbYes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbYes.setForeground(new java.awt.Color(255, 255, 255));
        lbYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbYes.setText("ĐỒNG Ý");

        javax.swing.GroupLayout pYesLayout = new javax.swing.GroupLayout(pYes);
        pYes.setLayout(pYesLayout);
        pYesLayout.setHorizontalGroup(
            pYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbYes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pYesLayout.setVerticalGroup(
            pYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbYes, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        pNo.setBackground(new java.awt.Color(255, 153, 0));
        pNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pNoMouseClicked(evt);
            }
        });

        lbNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNo.setForeground(new java.awt.Color(255, 255, 255));
        lbNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNo.setText("TỪ CHỐI");

        javax.swing.GroupLayout pNoLayout = new javax.swing.GroupLayout(pNo);
        pNo.setLayout(pNoLayout);
        pNoLayout.setHorizontalGroup(
            pNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pNoLayout.setVerticalGroup(
            pNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        lbThongBao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbThongBao1.setForeground(new java.awt.Color(255, 255, 255));
        lbThongBao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongBao1.setText("Đang tìm kiếm.......");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbwelcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(lbThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pYes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lbThongBao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbThongBao1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(pYes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pYesMouseClicked
        // TODO add your handling code here:
        lbYes.setText("Đang kết nối");
        try {
            out.write("Pair:yes");
            out.newLine();
            out.flush();
        } catch (Exception e) {
        }
        //new ClientGUI(id,s).setVisible(true);
    }//GEN-LAST:event_pYesMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:               
                out.write("Pair:exit");
                out.newLine();
                out.flush();                            
                this.dispose();            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void pNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pNoMouseClicked
        // TODO add your handling code here:
        try {
            out.write("Pair:no");
            out.newLine();
            out.flush();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_pNoMouseClicked
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaitRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaitRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaitRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaitRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaitRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNo;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbThongBao1;
    private javax.swing.JLabel lbYes;
    private javax.swing.JLabel lbwelcome;
    private javax.swing.JPanel pNo;
    private javax.swing.JPanel pYes;
    // End of variables declaration//GEN-END:variables
}
